apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1"
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432


---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: my-postgres
  ports:
    - port: 5432
      targetPort: 5432

